<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ModName>ModulusModLoader</ModName>
    <AssemblyName>$(ModName)</AssemblyName>
    <RootNamespace>ModulusModLoader</RootNamespace>
    <TargetFramework>net48</TargetFramework>
    <Version>0.2.0</Version>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)..\ModulusModLoader.VS.props" />
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)..\ModulusModLoader.VS.References.props" />
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
